### ISSUE TITLE
Improve the move method

### ISSUE THREAD

**Issue by RobertAudi** [maid/maid#119]
Right now, the move method overwrites the file at the destination if it exists. It would be better if the `move` method checks for the existence of the file at the destination and potentially renames the file(s) (by appending a number at the end for example).

That's what I am using at the moemnt as a replacement for the move method:

``` ruby
# destination must be a dir!
def mvr(file, destination)
  destination = File.expand_path(destination)
  if File.file?(file) && File.directory?(destination)
    extension = File.extname(file)
    filename = File.basename(file, extension)
    full_filename = filename + extension
    file_dir  = File.dirname(file)
    counter = 1

    while File.file?(File.join(destination, full_filename))
      full_filename = "#{filename}_#{counter.to_s + extension}"
      counter += 1
    end

    new_file = File.join(destination, full_filename)

    FileUtils.mv(file, new_file, force: true)

    directory = destination.split("/").last
    true
  else
    false
  end
end
```

**Comment by coaxial** [comment]
Going through old issues and triaging.

Is there still any interest for this feature? If so, please chime in as popularity will influence implementation prioritization in a future release.
