### ISSUE TITLE
Maid understand natural language (English...)!

### ISSUE THREAD

**Issue by btwael** [maid/maid#122]
Maybe this is one of the most complex problem in computer science, however it will be nice to talk (I mean define rules) with [`maid`](https://github.com/benjaminoakes/maid) in natural language (English), very simple English, maybe something similar to [english-script](https://github.com/pannous/english-script) (it's written in ruby!), with enough verb and action to be like rules written in ruby!

**Comment by coaxial** [comment]
Going through old issues and triaging.

This is an interesting idea, although a rather complex and time-intensive one. I'll close for now as it is unlikely that I'll implement it but feel free to chime in if you're willing to work on this :)
