### ISSUE TITLE
Create Open Source Graphical Interface for OS X

### ISSUE THREAD

**Issue by bhagyas** [maid/maid#134]

**Comment by coaxial** [comment]
Closing as this is a very old issue and represents a lot of work in a domain I'm not familiar with. Feel free to chime in if there is still interest in this feature.

**Comment by benjaminoakes** [comment]
I have a repository for this with basically nothing in it. I may move it to the maid organization so that someone could step in and start work if they feel the urge to do so.  There's another one for Linux as well.
