### ISSUE TITLE
Add launch agent for OSX users

### ISSUE THREAD

**Issue by benjaminoakes** [maid/maid#136]
See [Maid as a Daemon on OS X](http://jurriaan.ninja/2015/01/01/maid-on-os-x.html)

Related: #126
CC: @jurriaan

**Comment by soleo** [comment]
@jurriaan @benjaminoakes  would it make more sense to integrate with homebrew , and use something like ``brew services start maid`` to Install and start the service at login

**Comment by benjaminoakes** [comment]
I'd be interested in seeing a pull request with this if anyone is interested in putting it together.

**Comment by malonehedges** [comment]
Would love to see this integrated into Homebrew. Is anyone going to work on this in the near future?

**Comment by coaxial** [comment]
Going through old issues and triaging.

Is there still an interest in this feature? Popularity will affect implementation prioritization.

**Comment by piersolenski** [comment]
Yes please!
