### ISSUE TITLE
create SPA to set rules

### ISSUE THREAD

**Issue by bronzelegs** [maid/maid#137]
like hazel does, but it would be better to have more control, i.e. instead of all/any rule set match, nested groups of all/any  ex: any 'jpg' 'png' -> all 'by access date' and 'from destination'

**Comment by coaxial** [comment]
Going through old issues and triaging.

Is there still an interest in this? If so, could you please expand on the feature? I'm not familiar with Hazel and don't quite understand what you mean.

**Comment by benjaminoakes** [comment]
I'm also uncertain, but I think they are requesting a single page application (SPA) to provide a web UI. Personally, I would feel more comfortable with something more Rails-like if we were to build a GUI.  (That is, light on the JavaScript.)

However this is just a guess

**Comment by coaxial** [comment]
That's a complex feature, I'm wondering how useful it would be. To write rules, you presumably need to know how to write ruby and therefore be comfortable using a text editor. It feels like it's out of scope for that project, especially given the limited bandwidth we have to move the project forward and the many other feature requests competing.

By all means, if someone wants to contribute we'd welcome a PR. But this is a large undertaking.

I'd be inclined to "close as not planned" for now and revisit if there is enough demand for it. Thoughts?
