### ISSUE TITLE
Color output

### ISSUE THREAD

**Issue by brandondrew** [maid/maid#139]
It would be easier to read the output of `maid clean` if the rule names were in one color and the comments regarding would would happen or is happening were in another color.  Perhaps a gray would be good for dry runs, and a brighter color would be good for actual results.

**Comment by benjaminoakes** [comment]
I'd be for this (pull requests welcome), but it needs to play nicely with logging and other non-interactive contexts.

**Comment by coaxial** [comment]
Going through old issues and triaging.

Is there still an interest for this feature? Popularity will affect implementation prioritization for a future release.
