### ISSUE TITLE
May you could help me?

### ISSUE THREAD

**Issue by MoritzFago** [maid/maid#147]
Hello

i want maid daemon to do when ever a new picture comes in the downloads folder (via AirDrop) which has the downloaded from attribute "\* iPhone" that it´s moved to a special folder. Here is my (not working) ruleset

``` ruby
Maid.rules do

  watch '/Users/moritzfago/Downloads' do
    rule 'AirDrop to Desktop' do |added|
      added.each do |path|
        move(path,'/Users/moritzfago/Desktop/AirDroped') if downloaded_from(path).any? { |u| u.match('.*iPhone.*')}
      end
    end
  end
end
```

can you tell my that i am doing wrong? I can´t find the error.

**Comment by benjaminoakes** [comment]
It looks like you want to use a regexp but are using a string instead.  Try changing `'.*iPhone.*'` to `/.*iPhone.*/`.

**Comment by benjaminoakes** [comment]
Also, the `rule` block doesn't take an argument.

**Comment by MoritzFago** [comment]
okay i really don´t know what´s wrong.
What i want is that every time a file is added to my downloads folder maid get´s these added files and checks if they were downloaded via AirDrop from an iOS device (this means the com.apple.metadata:kMDItemWhereFroms extended attribute is like this:
```
00000000  62 70 6C 69 73 74 30 30 A1 01 5D 4D 6F 72 69 74  |bplist00..]Morit|
00000010  7A 20 69 50 68 6F 6E 65 08 0A 00 00 00 00 00 00   |z iPhone........|
00000020  01 01 00 00 00 00 00 00 00 02 00 00 00 00 00 00    |................|
00000030  00 00 00 00 00 00 00 00 00 18                                  |..........|
0000003a
```
) and if thats true moves them to a special folder.

I think my code above should do that, but it doesn´t as far as i could debug this code
 ```
added.each do |path|
        move(path,'/Users/moritzfago/Desktop/AirDroped') if downloaded_from(path).any? { |u| u.match('.*iPhone.*')}
```
block isn´t executed and i don´t know why.

**Comment by MoritzFago** [comment]
oh by the way this is my rules.rb
```ruby
# Sample Maid rules file

Maid.rules do

  watch '/Users/moritzfago/Downloads' do
    rule 'AirDrop to Desktop' do
      added.each do |path|
        puts(path)
        move(path,'/Users/moritzfago/Desktop/AirDroped') if (downloaded_from(path).any? {|s| s[/.*iPhone.*/]})
      end
      puts 'ed'
    end
  end
end
```

**Comment by benjaminoakes** [comment]
Could you make this a question on StackOverflow, please?  It'd be more likely to get attention.  I'd recommend using the "maid" tag when you post it.

[Here's an example of another Maid user posting to StackOverflow.](http://stackoverflow.com/questions/25988567/how-do-i-copy-specific-file-types-with-maid/25989377)

**Comment by MoritzFago** [comment]
now it works, but it works only one time.

```ruby
# Sample Maid rules file

Maid.rules do

  watch '/Users/moritzfago/Downloads/' do
    #puts added
    rule 'AirDrop to Desktop' do |added, modified|
      puts 'foo'
      puts 'foo3'
      puts modified
      puts added
      puts 'foo2'
      added.each do |path|
        puts(path)
        if downloaded_from(path).any? {|s| s[/.*iPhone.*/]} then
          move(path,'/Users/moritzfago/Desktop/AirDroped')
        end
      end
      modified.each do |path|
        puts(path)
        if downloaded_from(path).any? {|s| s[/.*iPhone.*/]} then
          move(path,'/Users/moritzfago/Desktop/AirDroped')
        end
      end
      puts 'ed'
    end
  end
end
```
after it fired one time it doesn´t not work anymore. any ideas?

**Comment by coaxial** [comment]
Closing as this is very old. If still an issue, please try with version 0.9.0.alpha.2 (`gem install maid -v 0.9.0.alpha.2`) and comment.
