### ISSUE TITLE
Is there any dry-run option for maid daemon?

### ISSUE THREAD

**Issue by MoritzFago** [maid/maid#148]

**Comment by greenmountainkate** [comment]
From the [README](https://github.com/benjaminoakes/maid#readme):

> Before you start running your rules, you'll likely want to be able to test them. Here's how:
> ```
> # No actions are taken; you just see what would happen with your rules as defined.
> maid clean --dry-run # Synonyms: -n, --noop
> ```

**Comment by coaxial** [comment]
Closing as it has been answered.
