### ISSUE TITLE
Rename Duplicate Files When Moving

### ISSUE THREAD

**Issue by tech-otaku** [maid/maid#153]
I'm a long-time Hazel user having recently switched to Maid and I love the flexibility it offers. 

One downside I have is that when moving files, Maid overwrites a file in the target directory with the file it's moving if it has the same name. Hazel renamed any duplicate files.

Is this functionality something you'd consider adding to Maid? 

Thanks.

EDIT: Just noticed a thread entitled 'Improve the move method' https://github.com/benjaminoakes/maid/issues/119 by RobertAudi back in February 2014. Guess that answers my question.

**Comment by coaxial** [comment]
Closing and tracking in #119
