### ISSUE TITLE
add chown options to sync helper

### ISSUE THREAD

**Issue by sotaan** [maid/maid#155]
Is it possible to add the chown option from the rsync command into the `sync` helper method in `lib/maid/tools.rb` ?
This feature is very helpful when you need to build a custom rsync daemon.
Adding this line of code should work:
`ops << "--chown=#{ sh_escape(options[:chown]) }" if options[:chown]`

**Comment by coaxial** [comment]
Going through old issues and triaging.

What's the status on this @sotaan? I see there was a PR but it wasn't merged.
