### ISSUE TITLE
ERROR: directory is already being watched

### ISSUE THREAD

**Issue by haphap** [maid/maid#157]
Maid daemon fails when there are Mac Applications in the watched folder, error messages like that:

Directory: /Users/A/Downloads/Apps/duet.app/Contents/Frameworks/DevMateKit.framework/Frameworks/DevMateIssuesReporter.framework/Versions/A/Resources

is already begin watched through: /Users/A/Downloads/Apps/duet.app/Contents/Frameworks/DevMateKit.framework/Versions/A/Frameworks/DevMateIssuesReporter.framework/Versions/A/Resources

---

```
    ** ERROR: directory is already being watched! **

    Directory: /Users/HAP/Downloads/Apps/duet.app/Contents/Frameworks/Sparkle.framework/Versions/Current

    is already begin watched through: /Users/HAP/Downloads/Apps/duet.app/Contents/Frameworks/Sparkle.framework/Versions/A

    MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
```

E, [2016-05-14T23:53:49.931214 #737] ERROR -- : Actor crashed!
Encoding::CompatibilityError: incompatible character encodings: ASCII-8BIT and US-ASCII
    /usr/local/lib/ruby/gems/2.3.0/gems/listen-2.10.1/lib/listen/record/symlink_detector.rb:34:in `format'
    /usr/local/lib/ruby/gems/2.3.0/gems/listen-2.10.1/lib/listen/record/symlink_detector.rb:34:in`_fail'
    /usr/local/lib/ruby/gems/2.3.0/gems/listen-2.10.1/lib/listen/record/symlink_detector.rb:28:in `verify_unwatched!'
    /usr/local/lib/ruby/gems/2.3.0/gems/listen-2.10.1/lib/listen/record.rb:119:in`_fast_build_dir'
    /usr/local/lib/ruby/gems/2.3.0/gems/listen-2.10.1/lib/listen/record.rb:113:in `_fast_build'
    /usr/local/lib/ruby/gems/2.3.0/gems/listen-2.10.1/lib/listen/record.rb:67:in`block in build'
    /usr/local/lib/ruby/gems/2.3.0/gems/listen-2.10.1/lib/listen/record.rb:66:in `each'
    /usr/local/lib/ruby/gems/2.3.0/gems/listen-2.10.1/lib/listen/record.rb:66:in`build'
    /usr/local/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
    /usr/local/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in`dispatch'
    /usr/local/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
    /usr/local/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in`block in invoke'
    /usr/local/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
    /usr/local/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in`block in task'
    /usr/local/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
    /usr/local/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in`block in create'
/usr/local/lib/ruby/gems/2.3.0/gems/listen-2.10.1/lib/listen/record/symlink_detector.rb:34:in `format': incompatible character encodings: ASCII-8BIT and US-ASCII (Encoding::CompatibilityError)
    from /usr/local/lib/ruby/gems/2.3.0/gems/listen-2.10.1/lib/listen/record/symlink_detector.rb:34:in`_fail'
    from /usr/local/lib/ruby/gems/2.3.0/gems/listen-2.10.1/lib/listen/record/symlink_detector.rb:28:in `verify_unwatched!'
    from /usr/local/lib/ruby/gems/2.3.0/gems/listen-2.10.1/lib/listen/record.rb:119:in`_fast_build_dir'
    from /usr/local/lib/ruby/gems/2.3.0/gems/listen-2.10.1/lib/listen/record.rb:113:in `_fast_build'
    from /usr/local/lib/ruby/gems/2.3.0/gems/listen-2.10.1/lib/listen/record.rb:67:in`block in build'
    from /usr/local/lib/ruby/gems/2.3.0/gems/listen-2.10.1/lib/listen/record.rb:66:in `each'
    from /usr/local/lib/ruby/gems/2.3.0/gems/listen-2.10.1/lib/listen/record.rb:66:in`build'
    from /usr/local/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
    from /usr/local/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in`dispatch'
    from /usr/local/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
    from /usr/local/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in`block in invoke'
    from /usr/local/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
    from /usr/local/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in`block in task'
    from /usr/local/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
    from /usr/local/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in`block in create'
    from (celluloid):0:in `remote procedure call'
    from /usr/local/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in`value'
    from /usr/local/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
    from /usr/local/lib/ruby/gems/2.3.0/gems/listen-2.10.1/lib/listen/listener.rb:91:in`block in class:Listener'
    from /usr/local/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/fsm.rb:175:in `instance_eval'
    from /usr/local/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/fsm.rb:175:in`call'
    from /usr/local/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/fsm.rb:127:in `transition_with_callbacks!'
    from /usr/local/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/fsm.rb:95:in`transition'
    from /usr/local/lib/ruby/gems/2.3.0/gems/listen-2.10.1/lib/listen/listener.rb:100:in `start'
    from /usr/local/lib/ruby/gems/2.3.0/gems/maid-0.8.0.alpha.4/lib/maid/watch.rb:33:in`run'
    from /usr/local/lib/ruby/gems/2.3.0/gems/maid-0.8.0.alpha.4/lib/maid/maid.rb:103:in `each'
    from /usr/local/lib/ruby/gems/2.3.0/gems/maid-0.8.0.alpha.4/lib/maid/maid.rb:103:in`daemonize'
    from /usr/local/lib/ruby/gems/2.3.0/gems/maid-0.8.0.alpha.4/lib/maid/app.rb:93:in `daemon'
    from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in`run'
    from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in`dispatch'
    from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /usr/local/lib/ruby/gems/2.3.0/gems/maid-0.8.0.alpha.4/bin/maid:5:in`<top (required)>'
    from /usr/local/bin/maid:23:in `load'
    from /usr/local/bin/maid:23:in`<main>'

**Comment by coaxial** [comment]
I am going through all open issues to try and triage.

Could you please try version `0.9.0.alpha.2` with `$ gem install maid -v 0.9.0.alpha.2` and report whether this is still happening?
