### ISSUE TITLE
Rename with created ISO date

### ISSUE THREAD

**Issue by AtomicNess123** [maid/maid#182]
Does maid support renaming prepending the ISO date of creation? Thanks.

**Comment by coaxial** [comment]
This should be possible with something like:

```ruby
require 'date'
move(path, File.join(File.dirname(path), "#{DateTime.now.iso8601}-#{File.basename(path)}"))
```

Which would rename `/path/to/my.file` to `/path/to/2023-03-19T13:12:45+01:00-my.file`. You can tweak the output format to your liking (see https://devdocs.io/ruby~3.1/datetime#method-i-strftime)
