### ISSUE TITLE
Linux compatibility page on wiki is out of date

### ISSUE THREAD

**Issue by coaxial** [maid/maid#203]
Here: https://github.com/maid/maid/wiki/Linux-compatibility

The page should be updated to mention the gem is tested on ubuntu-{20,22}.04 and macos-{11,12}. Or maybe it's not necessary anymore altogether? I don't know if all Linux distributions use standard paths for the trash, for instance.

**Comment by benjaminoakes** [comment]
They hopefully all use XDG at this point, but I'm also unsure

**Comment by coaxial** [comment]
I have updated the wiki page, closing.
