### ISSUE TITLE
Roadmap out of date

### ISSUE THREAD

**Issue by coaxial** [maid/maid#205]
Here: https://github.com/maid/maid/wiki/Roadmap

Dates from 2012, might not even be relevant anymore if we're aiming for maintenance mode; otherwise new features could be planned on that page.

**Comment by benjaminoakes** [comment]
Wow, this is ancient.

**Comment by coaxial** [comment]
I deleted the page altogether as it was so outdated. If we ever feel like we need a roadmap again, we can recreate it from scratch.

**Comment by benjaminoakes** [comment]
If I were to do this again, I might choose GitHub issues and Projects. For your consideration as any needs arise.
