### ISSUE TITLE
Stale issues aren't pruned

### ISSUE THREAD

**Issue by coaxial** [maid/maid#211]
Stale issues aren't pruned, would help lower the maintenance burden to have one of these bots that ping people for updates or close the issue as stale if there is no response (and reopens if they chime in).

**Comment by benjaminoakes** [comment]
I'm doing some related thinking on another project.  Do you have a preference for a particular bot or would you like my input once I've done more thinking?

**Comment by coaxial** [comment]
I haven't looked into this yet, so if you've figured anything out I'd be interested to learn from you.

**Comment by benjaminoakes** [comment]
What I'm trying on the other project https://github.com/marketplace/actions/close-stale-issues

It's the official GitHub solution for this problem.
