### ISSUE TITLE
The project and organization have no icon

### ISSUE THREAD

**Issue by coaxial** [maid/maid#241]
An icon would be dope, we could include it in the readme and use it for the maid org and repo on GitHub instead of the generic icon it has now.

**Comment by benjaminoakes** [comment]
Agreed! The Twitter avatar is about as close as we have. It's a little USB-powered vacuum.  Maybe a stylized version of that?

https://twitter.com/maidgem

**Comment by coaxial** [comment]
See #242

**Comment by coaxial** [comment]
Done a while back
