### ISSUE TITLE
Add tool to empty trash (first in, first out)

### ISSUE THREAD

**Issue by benjaminoakes** [maid/maid#26]
I don't need files in the trash that are there for a while...  but I'm more likely to need the ones I just threw away.  The only option I'm given is "empty trash" in the Finder or Nautilus, which gets rid of _everything_.

It'd be nice if Maid could get rid of the older trash first.

**Comment by coaxial** [comment]
This is how I'm doing it:

```ruby
  rule 'Empty trash' do
    dir('~/.local/share/Trash/files/*').each do |file|
      remove(file) if TRASH_MAX_AGE.since?(accessed_at(file))
    end
  end
```

Is there interest for a dedicated action to do this? Comment if so, popularity will influence implementation prioritization.

**Comment by benjaminoakes** [comment]
I know that macOS offers a similar feature now. I am not sure about Linux distributions, but I would not be surprised if Nautilus has something like it too.
