### ISSUE TITLE
Encourage collaboration with filesortd developers

### ISSUE THREAD

**Issue by benjaminoakes** [maid/maid#85]
Dear @myfreeweb,

Someone recently shared your `filesortd` project with me, and I have to say that I'm a fan.  It's great to know that so many people are interested in a Ruby-based Hazel-like program.  Your implementation of this concept has many great ideas and great code.

As the current maintainer of Maid, I'd like to do my part and reach out to you.  I'd love to find a way to cooperate toward our common goal.  I'm very open to your ideas, and if there's anything I can do to encourage this collaboration, I'd like to do so.

When I started Maid, my goal was to scratch my own itch.  I feel very fortunate to know that a growing community of people have found it interesting.  I think it would be great if we could serve that community by working together.

Clearly, Maid and `filesortd` are taking different approaches (right now), but it seems like they're complimentary approaches.  For example, many people run their Maid rules manually or with `cron`.  That was a quick way to get Maid off the ground, but I've personally wanted `fsevent` / `inotify` support for a while now.  You've done great work on that front.

I'd like to start a discussion about where we can go from here.  If you're interested in joining forces, I think we can make great things happen.

Best wishes,

@benjaminoakes

**Comment by benjaminoakes** [comment]
https://github.com/valpackett/filesortd

Sounds right. They may have some related code that we could use if the license is compatible, however.

**Comment by coaxial** [comment]
> code that we could use if the license is compatible

It is MIT licensed (https://github.com/valpackett/filesortd/blob/master/LICENSE.txt#L3) so I'd say it is.

**Comment by valpackett** [comment]
Oh wow, the memories from a literal decade ago! Haha. Cool to see that this project is still active! Yeah, if there's still anything somehow useful in there, feel free to just take it and make it yours.
