### ISSUE TITLE
sync exclude not running correctly

### ISSUE THREAD

**Issue by phoolish** [maid/maid#93]
I've noticed when I run the sync tool my exclude pattern is ignored.  I'll take a look at it this weekend.

**Comment by coaxial** [comment]
Going through old issues and triaging.

Could you please try installing the latest alpha version with `gem install maid -v 0.9.0.alpha.2 && maid --version` and report if so?

**Comment by coaxial** [comment]
@phoolish ping ^

**Comment by phoolish** [comment]
@coaxial I haven't used maid in 8-9 years. You are welcome to close the ticket.

**Comment by coaxial** [comment]
FWIW, Maid now runs on Ruby 3 so feel free to give it another go and see if it can be useful to you again :)
